# Generated by Django 4.2.9 on 2025-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_opd', models.CharField(max_length=20, unique=True)),
                ('nama_opd', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OPD',
                'verbose_name_plural': 'OPD',
                'ordering': ['nama_opd'],
            },
        ),
    ]
