# Generated by Django 4.2.9 on 2025-04-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menu_role_userprofile_submenu_rolepermission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuaccess',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='menuaccess',
            constraint=models.UniqueConstraint(fields=('menu', 'submenu', 'user', 'role', 'opd'), name='unique_menu_access'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'menu', 'submenu'), name='unique_role_menu_submenu'),
        ),
        migrations.RemoveField(
            model_name='menuaccess',
            name='group',
        ),
    ]
