# Generated by Django 4.2.9 on 2025-05-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_menuaccess_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuaccess',
            name='unique_menu_access',
        ),
        migrations.RemoveField(
            model_name='menuaccess',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuaccess',
            name='submenu',
        ),
        migrations.AddConstraint(
            model_name='menuaccess',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'opd'), name='unique_menu_access'),
        ),
    ]
